//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenCapturer.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenCapturer.Localizations.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved screenshots, do you want to save them?.
        /// </summary>
        internal static string dialog_closingProgram_UnsavedContent {
            get {
                return ResourceManager.GetString("dialog_closingProgram_UnsavedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved data!.
        /// </summary>
        internal static string dialog_closingProgram_UnsavedTitle {
            get {
                return ResourceManager.GetString("dialog_closingProgram_UnsavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of this program is already running!.
        /// </summary>
        internal static string dialog_MultipleInstance_Content {
            get {
                return ResourceManager.GetString("dialog_MultipleInstance_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenCapturer is not taking screenshots..
        /// </summary>
        internal static string notificationIcon_IsNotTakingShots {
            get {
                return ResourceManager.GetString("notificationIcon_IsNotTakingShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenCapturer is taking screenshots..
        /// </summary>
        internal static string notificationIcon_IsTakingShots {
            get {
                return ResourceManager.GetString("notificationIcon_IsTakingShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shots to save....
        /// </summary>
        internal static string notificationIcon_NoFilesToSave {
            get {
                return ResourceManager.GetString("notificationIcon_NoFilesToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved shots to \&quot;{0}\&quot;.
        /// </summary>
        internal static string notificationIcon_SavedFiles {
            get {
                return ResourceManager.GetString("notificationIcon_SavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0} shots to file....
        /// </summary>
        internal static string notificationIcon_SavingFiles {
            get {
                return ResourceManager.GetString("notificationIcon_SavingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC has started taking screenshots....
        /// </summary>
        internal static string notificationIcon_StartedShooting {
            get {
                return ResourceManager.GetString("notificationIcon_StartedShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC has stopped taking screenshots....
        /// </summary>
        internal static string notificationIcon_StoppedShooting {
            get {
                return ResourceManager.GetString("notificationIcon_StoppedShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenCapturer.
        /// </summary>
        internal static string program_Name {
            get {
                return ResourceManager.GetString("program_Name", resourceCulture);
            }
        }
    }
}
